# -*- coding: utf-8 -*-
"""Hand-written Vietnamese translations for the N3 grammar reference.
MEANING_VI: pattern (as on jlptsensei list) -> short Vietnamese meaning.
EXAMPLE_VI: Japanese example sentence (whitespace removed) -> Vietnamese translation.
"""
MEANING_VI = {
"上げる（あげる）": "làm xong, hoàn thành (việc gì)",
"あまり": "vì quá… nên…",
"あまりにも": "quá mức, quá đỗi…",
"合う（あう）": "cùng nhau làm…, lẫn nhau",
"ばいい": "nên…, chỉ cần… là được",
"ばよかった": "giá mà đã…, lẽ ra nên…",
"ば～ほど": "càng… càng…",
"ば～のに": "giá mà… thì đã…",
"ばかりで": "chỉ toàn… (ý tiêu cực)",
"ばかりでなく": "không chỉ… mà còn…",
"べきだ": "nên…, phải… (bổn phận)",
"べきではない": "không nên…",
"別に～ない（べつに～ない）": "không hẳn…, không đặc biệt…",
"ぶりに": "lần đầu sau (khoảng thời gian)…",
"中（ちゅう）": "đang…, trong lúc…, trong vòng…",
"だけ": "chỉ…, hết mức có thể…",
"だけでなく": "không chỉ… mà còn…",
"だけど": "nhưng, tuy nhiên…",
"だらけ": "đầy…, toàn là… (điều không mong muốn)",
"どんなに～ても": "dù… đến đâu đi nữa",
"どうしても": "bằng mọi giá, dù thế nào cũng…; mãi mà không…",
"ふりをする": "giả vờ…, làm ra vẻ…",
"ふと": "bỗng nhiên, chợt…",
"がち": "hay…, có xu hướng…, dễ bị…",
"がたい": "khó mà…, khó có thể…",
"気味（ぎみ）": "hơi có vẻ…, có chiều hướng…",
"ごとに": "mỗi…, cứ mỗi…",
"ほど": "đến mức…, khoảng…",
"ほど～ない": "không… bằng…",
"一度に（いちどに）": "cùng một lúc, một lần",
"いくら～ても": "dù có… bao nhiêu đi nữa",
"一方だ（いっぽうだ）": "ngày càng…, chỉ có… (một chiều)",
"一体（いったい）": "rốt cuộc là…, cái quái gì…",
"じゃない": "chẳng phải… sao?; có lẽ…",
"か何か（かなにか）": "… hay gì đó",
"かける": "đang làm dở…, sắp…, chưa xong",
"から〜にかけて": "từ… đến…, suốt từ… tới…",
"代わりに（かわりに）": "thay vì…, thay cho…, bù lại…",
"結果（けっか）": "kết quả là…, sau khi…",
"結局（けっきょく）": "rốt cuộc, cuối cùng thì…",
"決して～ない（けっして～ない）": "tuyệt đối không…, quyết không…",
"切れない（きれない）": "không thể… hết, không… nổi",
"きり": "chỉ…; kể từ khi… (không còn…)",
"切る（きる）": "làm… hết hẳn, làm… đến cùng",
"っけ": "… nhỉ? (xác nhận điều đang cố nhớ)",
"込む（こむ）": "… vào trong; … miệt mài, lâu",
"こそ": "chính là…, mới là… (nhấn mạnh)",
"こと": "hãy…, phải… (quy định, chỉ thị)",
"ことから": "từ việc…, vì…",
"ことになっている": "theo quy định là…, dự định là…",
"ことはない": "không cần phải…; không bao giờ…",
"ことは～が": "… thì có… nhưng…",
"くらい / ぐらい": "khoảng…, đến mức…",
"くせに": "vậy mà…, thế mà… (trách móc)",
"まるで": "cứ như là…, hệt như…",
"まさか": "không lẽ…, chẳng lẽ…, làm gì có chuyện…",
"めったに～ない": "hiếm khi…, ít khi…",
"も～ば～も": "vừa… vừa…, cả… lẫn…",
"もしかしたら": "có lẽ, biết đâu…",
"もしも〜たら": "nếu như…, giả sử…",
"向け（むけ）": "dành cho…, hướng tới…",
"向き（むき）": "thích hợp với…, hợp cho…",
"むしろ": "thà rằng…, đúng hơn là…",
"ながらも": "tuy… nhưng…, mặc dù…",
"ないことはない": "không phải là không…, cũng có thể…",
"ないと": "phải…, nếu không… thì…",
"なかなか": "khá là…; mãi mà không…",
"なんか / なんて / など": "… chẳng hạn, … các thứ (coi nhẹ, ví dụ)",
"直す（なおす）": "làm lại…, … lại",
"なるべく": "cố gắng…, càng… càng tốt",
"なぜなら": "bởi vì, lý do là…",
"んだって": "nghe nói là…",
"に違いない（にちがいない）": "chắc chắn là…, không nghi ngờ gì…",
"に反して（にはんして）": "trái với…, ngược lại với…",
"にかけて": "suốt đến…, về mặt…",
"に関する / に関して（にかんする / にかんして）": "liên quan đến…, về…",
"にかわって / にかわり": "thay cho…, thay mặt…",
"に比べて（にくらべて）": "so với…",
"に慣れる（になれる）": "quen với…",
"において / における": "tại…, ở…, trong (lĩnh vực)…",
"にしたがって": "theo…, cùng với…, tuân theo…",
"にしても": "cho dù…, dù là…",
"にしては": "so với mức… thì…, đối với… mà nói",
"に対して（にたいして）": "đối với…, trái lại với…",
"にとって": "đối với… (quan điểm)",
"について": "về…, liên quan đến…",
"につれて": "cùng với…, càng… càng…",
"には": "để…, đối với việc…",
"によると /によれば": "theo… (nguồn tin)",
"によって / による": "bởi…, do…, tùy theo…, bằng…",
"のでしょうか": "… phải chăng?, liệu có… không? (hỏi lịch sự)",
"を中心に（をちゅうしんに）": "lấy… làm trung tâm, tập trung vào…",
"をはじめ": "bắt đầu từ…, tiêu biểu là…",
"を込めて（をこめて）": "dồn hết…, chứa đựng…",
"を通じて / を通して（をつうじて / をとおして）": "thông qua…, suốt…",
"おかげで": "nhờ có…, nhờ vào…",
"っぱなし": "để nguyên…, bỏ mặc… (không dọn)",
"っぽい": "có vẻ…, giống như…, dễ…",
"さえ": "ngay cả…, đến cả…",
"さえ～ば": "chỉ cần… là…",
"際に（さいに）": "khi…, vào lúc…, nhân dịp…",
"最中に（さいちゅうに）": "đang lúc…, ngay giữa lúc…",
"さらに": "hơn nữa, thêm nữa…",
"さて": "nào, vậy thì… (chuyển đề tài)",
"せいで": "tại vì…, do… (kết quả xấu)",
"せいぜい": "nhiều lắm cũng chỉ…, cùng lắm là…",
"しばらく": "một lúc, một thời gian",
"しかない": "chỉ còn cách…, đành phải…",
"そのために": "vì thế, vì mục đích đó…",
"それとも": "hay là…, hoặc là…",
"そうもない /そうにない": "có vẻ không thể…, không có vẻ gì là…",
"すでに": "đã…, đã… rồi",
"すなわち": "tức là, nghĩa là…",
"数量 + は（すうりょう + は）": "ít nhất là… (số lượng)",
"たものだ": "đã từng hay…, trước đây thường…",
"たとたん": "ngay khi…, vừa mới… thì…",
"たびに": "mỗi lần…, cứ hễ… là…",
"ために": "để…, vì…, do…",
"確かに（たしかに）": "quả thật là…, đúng là…",
"たて": "vừa mới… xong",
"たとえ～ても": "cho dù… đi nữa",
"例えば（たとえば）": "ví dụ như…",
"たって": "cho dù…, dẫu có…",
"てばかりいる": "chỉ toàn…, suốt ngày chỉ…",
"てごらん": "thử… xem",
"てはじめて": "chỉ sau khi… mới…",
"てからでないと": "nếu chưa… thì không thể…",
"てしょうがない・てしかたがない": "… không chịu được, … vô cùng",
"て済む（てすむ）": "chỉ cần… là xong, … là ổn",
"てはいけないから": "vì không được…, để tránh…",
"ている場合じゃない（ているばあいじゃない）": "không phải lúc để…",
"的（てき）": "mang tính…, thuộc về… (tạo tính từ -na)",
"ても始まらない（てもはじまらない）": "dù có… cũng vô ích",
"ても構わない（てもかまわない）": "… cũng không sao",
"てもしょうがない / てもしかたがない": "dù có… cũng chẳng ích gì",
"と言えば（といえば）": "nói đến…, nhắc đến…",
"といい / たらいい": "mong là…, giá mà…, nên…",
"といっても": "tuy nói là… nhưng…",
"ということだ": "nghe nói là…; nghĩa là…",
"というのは": "… nghĩa là; sở dĩ… là vì…",
"と言うと（というと）": "nói đến… thì…",
"というより": "thay vì nói là… thì đúng hơn là…",
"とみえる / とみえて": "có vẻ như…, xem ra…",
"とすれば・としたら・とすると": "nếu như…, giả sử…",
"と共に（とともに）": "cùng với…, đồng thời…",
"途中で/途中に（とちゅうで/とちゅうに）": "giữa chừng…, trên đường…",
"ところで": "nhân tiện, à này…",
"ところが": "thế nhưng, vậy mà…",
"とおりに": "đúng như…, theo như…",
"通す（とおす）": "… đến cùng, … suốt",
"として": "với tư cách là…, là…",
"とても～ない": "không thể nào…",
"とは限らない（とはかぎらない）": "không hẳn là…, chưa chắc…",
"つい": "lỡ…, trót…, vô tình…",
"ついに": "cuối cùng thì…, rốt cuộc…",
"ついでに": "nhân tiện…, tiện thể…",
"つまり": "tóm lại, tức là…",
"つもりだった": "đã định…, cứ tưởng là…",
"つもりで": "với ý định…, coi như là…",
"うちに": "trong khi…, nhân lúc…, trước khi…",
"上で（うえで）": "sau khi…; trong việc…",
"上に（うえに）": "hơn nữa…, không những… mà còn…",
"は別として（はべつとして）": "ngoại trừ…, chưa bàn đến…",
"はもちろん": "… thì khỏi phải nói, không chỉ… mà…",
"は～で有名（は～でゆうめい）": "… nổi tiếng về…",
"わけだ": "thảo nào…, tức là…, hèn gì…",
"わけではない": "không có nghĩa là…, không hẳn là…",
"わけがない": "không thể nào…, làm gì có chuyện…",
"わけにはいかない": "không thể… (vì lý do), đành phải…",
"割に（わりに）": "so với… thì…, tuy… nhưng…",
"わざと": "cố ý, cố tình",
"わざわざ": "mất công…, cất công…",
"よりも": "hơn là…, so với…",
"ようがない": "không có cách nào…, không thể…",
"ような気がする（ようなきがする）": "có cảm giác như…, hình như…",
"ように": "để…, sao cho…",
"ように見える（ようにみえる）": "trông có vẻ…, trông như…",
"ようとしない": "không chịu…, không có ý định…",
"ようとする": "định…, cố gắng…, sắp…",
"ずに": "mà không…",
"ずにはいられない": "không thể không…, không kìm được…",
"ずつ": "mỗi…, từng…",
}

from grammar_examples_vi import EXAMPLE_VI  # noqa: E402,F401
