# -*- coding: utf-8 -*-
"""Hand-written Vietnamese translations of grammar example sentences (jlptsensei N3 list).
Key: Japanese sentence with whitespace removed (as stored in grammar_crawl.json)."""
EXAMPLE_VI = {
"彼女は小説を書き上げた。": "Cô ấy đã viết xong cuốn tiểu thuyết.",
"嬉しさのあまり、彼女は涙を流しました。": "Vì quá vui mừng, cô ấy đã rơi nước mắt.",
"最近あまりに暑すぎる。": "Dạo này trời nóng quá mức.",
"私たちはその件について話し合いましょう。": "Chúng ta hãy cùng bàn bạc về việc đó.",
"どうすればいいですか？": "Tôi nên làm thế nào thì được?",
"そうすればよかった。": "Giá mà tôi đã làm như vậy.",
"ビートルズの音楽は聞けば聞くほど好きになります。": "Nhạc của The Beatles càng nghe càng thích.",
"このかばん、欲しいけど高いなあ。もっと安ければいいのに。": "Cái túi này, muốn mua nhưng đắt quá. Giá mà rẻ hơn một chút thì tốt.",
"夏は暑いばかりで楽しくないですよ。": "Mùa hè chỉ toàn nóng nực, chẳng vui gì cả.",
"このマンションは狭いばかりでなく、暗いです。": "Căn hộ này không chỉ chật mà còn tối.",
"私はそれについてもっと知るべきだ。": "Tôi nên biết nhiều hơn về điều đó.",
"それは別に悪いことでもない。": "Điều đó cũng không hẳn là chuyện xấu.",
"私は一晩中泣いていた。": "Tôi đã khóc suốt cả đêm.",
"ここのレストランはどれも安いだけでなく、美味しい。": "Nhà hàng ở đây món nào cũng không chỉ rẻ mà còn ngon.",
"スキー行きたいんだけど、お金が全然ないよ。": "Tôi muốn đi trượt tuyết, nhưng chẳng có đồng nào cả.",
"この公園は、猫だらけだ。": "Công viên này toàn là mèo.",
"彼は聞こえないふりをした。": "Anh ta giả vờ như không nghe thấy.",
"ふと街で彼に会った。": "Tôi tình cờ gặp anh ấy trên phố.",
"私は、仕事でミスしがちです。": "Tôi hay mắc lỗi trong công việc.",
"信じがたいことだが、これは事実だ。": "Thật khó tin, nhưng đây là sự thật.",
"彼は人の名前を忘れ気味である。": "Anh ấy có xu hướng hay quên tên người khác.",
"バスは１０分ごとに通っている。": "Cứ 10 phút lại có một chuyến xe buýt.",
"君ほど美しい人はいません！": "Không có ai đẹp bằng em!",
"彼女ほど優しい人はいない。": "Không ai hiền dịu như cô ấy.",
"お金はいくらあっても困りません。": "Tiền có bao nhiêu cũng không thừa.",
"最近、この町の人口は減る一方だ。": "Gần đây, dân số thị trấn này ngày càng giảm.",
"彼は病気か何かだろう。": "Chắc anh ấy bị ốm hay gì đó.",
"お風呂に入りかけたときに電話が鳴った。": "Lúc tôi vừa định vào bồn tắm thì điện thoại reo.",
"東京から京都にかけて新幹線で行くのは何時間かかるの？": "Đi tàu shinkansen từ Tokyo đến Kyoto mất mấy tiếng?",
"私が部長の代わりに出張に行きます。": "Tôi sẽ đi công tác thay cho trưởng phòng.",
"彼は仕事をサボった結果として首になった。": "Kết quả của việc trốn việc là anh ta bị sa thải.",
"結局彼はそれを買わなかった。": "Rốt cuộc anh ấy đã không mua cái đó.",
"あなたのことは決して忘れません。": "Tôi sẽ không bao giờ quên bạn.",
"この部屋に100人は入り切れない。": "Phòng này không chứa nổi 100 người.",
"私は一人きりで暮らすのが嫌だ。": "Tôi ghét sống một mình.",
"どうしてそう言い切れるのですか。": "Sao bạn có thể khẳng định chắc chắn như vậy?",
"次のテストっていつだっけ？": "Bài kiểm tra tới là khi nào nhỉ?",
"この紙に必要な情報を書き込んでください。": "Hãy điền thông tin cần thiết vào tờ giấy này.",
"これこそ望むところです。": "Đây chính là điều tôi mong muốn.",
"この図書館では2週間まで本が借りられることになっています。": "Ở thư viện này, theo quy định có thể mượn sách tối đa 2 tuần.",
"謝ることはないよ。": "Không cần phải xin lỗi đâu.",
"パーティーは行けることは行けるが、たぶん1時間くらい遅刻する。": "Tiệc thì đi được đấy, nhưng chắc tôi sẽ đến muộn khoảng 1 tiếng.",
"どれくらい日本に住んでいますか？": "Bạn sống ở Nhật được bao lâu rồi?",
"背が高いくせに早く走れない。": "Cao thế mà lại chạy không nhanh.",
"合格した！まるで夢のようだ。": "Đậu rồi! Cứ như là mơ vậy.",
"本を読むのが好きな人もいれば、嫌いな人もいます。": "Có người thích đọc sách, cũng có người ghét.",
"もしかしたら、明日行けないかもしれない。": "Có lẽ ngày mai tôi không đi được.",
"もしも明日は晴れたらピクニックに行きましょう。": "Nếu mai trời nắng thì mình đi dã ngoại nhé.",
"初心者向けのコースがありますか。": "Có khóa học dành cho người mới bắt đầu không?",
"私はむしろ一人で行きたい。": "Tôi thà đi một mình còn hơn.",
"狭いながらも、このマンションは大好きだ。": "Tuy chật nhưng tôi rất thích căn hộ này.",
"走れば間に合わないことはないよ。急ごう！": "Nếu chạy thì không phải là không kịp đâu. Nhanh lên!",
"もう行かないと...": "Tôi phải đi rồi...",
"なかなか面白そうです。": "Có vẻ khá thú vị đấy.",
"試験も近いし、テレビなど見ている暇はない。": "Sắp thi rồi, không có thời gian mà xem tivi các thứ đâu.",
"この作文はミスが多いから、書き直したほうがいいよ。": "Bài văn này nhiều lỗi, nên viết lại thì hơn.",
"なるべく気をつけてください。": "Hãy cẩn thận hết mức có thể.",
"なぜなら彼は病気だったからです。": "Bởi vì anh ấy đã bị ốm.",
"彼、彼女ができたんだって。": "Nghe nói anh ấy có bạn gái rồi đấy.",
"それは痛いに違いない。": "Cái đó chắc chắn là đau lắm.",
"テニスにかけては、彼に勝てる人はいない。": "Về tennis thì không ai thắng được anh ấy.",
"それに関しては彼は初心者だ。": "Về việc đó thì anh ấy là người mới.",
"昨日に比べて、今日は少し寒いね。": "So với hôm qua, hôm nay hơi lạnh nhỉ.",
"私は全てにおいて頑張ります。": "Tôi sẽ cố gắng trong mọi việc.",
"暗くなるにしたがって、だんだん寒くなってきました。": "Trời càng tối thì càng lạnh dần.",
"どちらにしても賛成できない。": "Dù thế nào đi nữa tôi cũng không thể tán thành.",
"彼は女性に対しては優しい。": "Anh ấy dịu dàng với phụ nữ.",
"私にとって、漢字の勉強はとても楽しい。": "Đối với tôi, học kanji rất vui.",
"この問題についてどう思いますか。": "Bạn nghĩ gì về vấn đề này?",
"台風が近づくにつれて、どんどん風が強くなってきた。": "Bão càng đến gần, gió càng mạnh dần lên.",
"日本語が上手になるには、どうしたらいいですか。": "Để giỏi tiếng Nhật thì nên làm thế nào?",
"天気予報によると、明日は雨だそうです。": "Theo dự báo thời tiết, nghe nói mai trời mưa.",
"それは場合による。": "Cái đó còn tùy trường hợp.",
"明日は晴れるのでしょうか。": "Không biết ngày mai trời có nắng không nhỉ?",
"文法を中心に、日本語を勉強する。": "Học tiếng Nhật lấy ngữ pháp làm trọng tâm.",
"東京には東京タワーをはじめ多くの観光地がある。": "Ở Tokyo có nhiều điểm du lịch, tiêu biểu là tháp Tokyo.",
"そのことは新聞を通じて知った。": "Tôi biết chuyện đó qua báo chí.",
"彼女のおかげで、私は毎日幸せだ。": "Nhờ có cô ấy mà ngày nào tôi cũng hạnh phúc.",
"このドアはいつも開けっぱなしだ。": "Cánh cửa này lúc nào cũng bị để mở toang.",
"油っぽい食事は好きじゃない。": "Tôi không thích đồ ăn nhiều dầu mỡ.",
"そんなこと、子供でさえ知っている。": "Chuyện đó đến trẻ con cũng biết.",
"お金さえあれば幸せです。": "Chỉ cần có tiền là hạnh phúc.",
"あなたが日本へ来る際には連絡ください。": "Khi nào đến Nhật, hãy liên lạc với tôi nhé.",
"食事の最中に大きな地震が起こった。": "Đang lúc ăn cơm thì xảy ra động đất lớn.",
"彼は父親よりさらに背が高い。": "Anh ấy còn cao hơn cả bố mình.",
"さっきコーヒーを飲んだせいで、なかなか寝られません。": "Tại lúc nãy uống cà phê nên tôi mãi không ngủ được.",
"せいぜい頑張ろうね！": "Cố gắng hết sức nhé!",
"やるしかない。": "Chỉ còn cách làm thôi.",
"あなたは明日、そのための時間がありますか？": "Ngày mai bạn có thời gian cho việc đó không?",
"歩こうか,それとも車で行こうか？": "Đi bộ hay là đi ô tô đây?",
"先生、明日までに宿題ができそうにないんですが、もう少し待っていただけませんか。": "Thưa thầy, có vẻ em không thể làm xong bài tập trước ngày mai, thầy có thể đợi thêm một chút được không ạ?",
"子どものころはよく川で遊んだものだ。": "Hồi nhỏ tôi thường hay chơi ở sông.",
"家を出たとたん、雨が降ってきた。": "Vừa ra khỏi nhà thì trời đổ mưa.",
"この曲を聞くたびに、家族を思い出す。": "Mỗi lần nghe bài hát này, tôi lại nhớ đến gia đình.",
"日本へ旅行をするために、貯金しています。": "Tôi đang tiết kiệm tiền để đi du lịch Nhật Bản.",
"それは確かにそのように見えます。": "Quả thật trông nó đúng là như vậy.",
"焼きたてのパンは美味しいよ。ちょっと食べてみる？": "Bánh mì mới nướng ngon lắm. Ăn thử một chút không?",
"たとえ彼は忙しくても来るよ。": "Cho dù bận, anh ấy vẫn sẽ đến.",
"日本の食べ物は美味しいです。例えば、すしはすごく美味しい！": "Đồ ăn Nhật rất ngon. Ví dụ như sushi cực kỳ ngon!",
"タクシーに乗ったって間に合わないよ。": "Dù có đi taxi cũng không kịp đâu.",
"この猫は寝てばかりいます。": "Con mèo này chỉ toàn ngủ.",
"もう一度やってごらん。": "Thử làm lại lần nữa xem.",
"日本に来てはじめてラーメンを食べた。": "Đến Nhật rồi tôi mới lần đầu ăn ramen.",
"親の許可をもらってからでなければ、日本への留学が出来ない。": "Nếu chưa được bố mẹ cho phép thì không thể đi du học Nhật.",
"私はそれが気になってしょうがない。": "Tôi bận tâm chuyện đó không chịu được.",
"雨が降るといけないから傘を持って行きなさい。": "Lỡ trời mưa thì không hay, nên hãy mang ô theo.",
"もっと具体的なアイディアを出してください。": "Hãy đưa ra ý tưởng cụ thể hơn.",
"雨が降っても構わない。": "Trời mưa cũng không sao.",
"そこへ行ってもしかたがない。": "Có đến đó cũng chẳng ích gì.",
"ベトナムと言えば、バイクが多いですね。": "Nói đến Việt Nam là nghĩ ngay đến nhiều xe máy nhỉ.",
"あなたが気にいるといいな。": "Mong là bạn sẽ thích.",
"今週は忙しい、といっても先週ほどじゃない。": "Tuần này bận, tuy nói vậy nhưng không bằng tuần trước.",
"ニュースによると、明日は雨が降るということだ。": "Theo bản tin, nghe nói ngày mai trời sẽ mưa.",
"「コンビニ」というのはコンビニエンスストアのことだ。": "「Konbini」nghĩa là cửa hàng tiện lợi.",
"桜というと、花見だ。": "Nói đến hoa anh đào là nghĩ đến ngắm hoa.",
"彼はかっこいいというよりかわいい。": "Anh ấy dễ thương hơn là đẹp trai.",
"彼は病気だとみえる。": "Có vẻ như anh ấy bị ốm.",
"選ぶとすれば、僕はこれだな。": "Nếu phải chọn thì tôi chọn cái này.",
"私の人生は、ギターと共にある。": "Cuộc đời tôi gắn liền với cây đàn guitar.",
"ごはんを食べている途中に電話がかかってきた。": "Đang ăn cơm dở thì có điện thoại gọi đến.",
"ところで、今どこにいるの？": "Nhân tiện, bây giờ bạn đang ở đâu?",
"彼は言われたとおりにした。": "Anh ấy đã làm đúng như được bảo.",
"やると決めたことは最後までやり通すべきだ。": "Việc đã quyết làm thì nên làm đến cùng.",
"彼は教師として働いている。": "Anh ấy đang làm việc với tư cách là giáo viên.",
"そんなこと、私にはとても出来ない。": "Chuyện như vậy tôi không thể nào làm được.",
"先生の答えがいつも正しいとは限りません。": "Câu trả lời của thầy không hẳn lúc nào cũng đúng.",
"料理がおいしくてつい食べ過ぎた。": "Đồ ăn ngon quá nên tôi lỡ ăn quá nhiều.",
"ついに着いたのだ！": "Cuối cùng cũng đến nơi rồi!",
"買い物のついでに、本屋に寄りました。": "Nhân tiện đi mua sắm, tôi ghé qua hiệu sách.",
"彼は獣医、つまり、動物の医者です。": "Anh ấy là bác sĩ thú y, tức là bác sĩ của động vật.",
"言ったつもりだった。": "Tôi cứ tưởng là mình đã nói rồi.",
"冗談のつもりで言ったのです。": "Tôi nói với ý định đùa thôi.",
"明るいうちに、帰りましょう。": "Về nhà khi trời còn sáng thôi.",
"外国語を勉強する上で辞書はなくてはならないものだ。": "Trong việc học ngoại ngữ, từ điển là thứ không thể thiếu.",
"今日は曇っている上に風が強いので、とても寒く感じられる。": "Hôm nay trời âm u, hơn nữa gió lại mạnh nên cảm thấy rất lạnh.",
"彼女の料理は見た目は別として、味はとても美味しい。": "Món ăn của cô ấy, hình thức thì chưa bàn, nhưng vị thì rất ngon.",
"彼女は、勉強はもちろん料理もよくできる。": "Cô ấy học giỏi thì khỏi nói, nấu ăn cũng giỏi.",
"この学校はフットボールが強いことで有名です。": "Trường này nổi tiếng vì mạnh về bóng đá.",
"毎日ギターを弾くから上手に弾けるわけだ。": "Ngày nào cũng chơi guitar nên giỏi là phải.",
"料理が作れないわけではないが、忙しいからあまり作らない。": "Không phải là tôi không biết nấu ăn, chỉ là bận nên ít nấu.",
"彼はお金がないですから、家を買えるわけがない。": "Anh ấy không có tiền nên không thể nào mua được nhà.",
"明日はテストがあるから、ゲームをするわけにはいかない。": "Mai có bài kiểm tra nên không thể chơi game được.",
"彼は年のわりに元気だ。": "So với tuổi thì ông ấy khỏe đấy.",
"彼はわざと間違えた。": "Anh ta cố tình làm sai.",
"私が困っているとき、彼女はわざわざ助けてくれた。": "Khi tôi gặp khó khăn, cô ấy đã cất công giúp đỡ tôi.",
"兄は私よりも大きい。": "Anh trai tôi to hơn tôi.",
"どうにもしようがない。": "Chẳng còn cách nào cả.",
"それが本当のような気がする。": "Tôi có cảm giác điều đó là thật.",
"バスに乗り遅れないように早く出ました。": "Tôi ra khỏi nhà sớm để không lỡ xe buýt.",
"ドアを開けようとしたが、鍵がかかっていました。": "Tôi định mở cửa nhưng cửa đã bị khóa.",
"勉強せずに試験に受かった。": "Tôi đậu kỳ thi mà không học bài.",
"あの本を読まずにはいられない。": "Tôi không thể không đọc cuốn sách đó.",
"私たちは一歩ずつ進みましょう。": "Chúng ta hãy tiến từng bước một.",
"そんなことをすべきではない。": "Không nên làm chuyện như vậy.",
"今日、やく2週間ぶりに雨が降った。": "Hôm nay trời mưa, lần đầu sau khoảng 2 tuần.",
"食べたいだけ食べなさい。": "Muốn ăn bao nhiêu thì cứ ăn.",
"どんなに頑張っても、70点しか取れなかった。": "Dù cố gắng đến đâu, tôi cũng chỉ được 70 điểm.",
"彼は一度にクッキーを3つ取った。": "Anh ấy lấy 3 cái bánh quy cùng một lúc.",
"一体どこで彼に会ったんだ。": "Rốt cuộc là bạn gặp anh ta ở đâu vậy?",
"トムさんも来るじゃない？": "Tom cũng sẽ đến mà, đúng không?",
"大声を出さないこと。": "Không được nói to.",
"道路が濡れていることから、雨が降ったということが分かる。": "Từ việc đường ướt, có thể biết là trời đã mưa.",
"まさかそうなるとは思わなかった。": "Tôi không ngờ sự việc lại thành ra như vậy.",
"彼はめったに本を読まない。": "Anh ấy hiếm khi đọc sách.",
"この本は初心者向きである。": "Cuốn sách này thích hợp cho người mới bắt đầu.",
"彼の話は事実に反する。": "Lời anh ta nói trái với sự thật.",
"弟は、母にかわってご飯を作った。": "Em trai tôi đã nấu cơm thay cho mẹ.",
"私は日本の生活に慣れるまでが大変だった。": "Cho đến khi quen với cuộc sống ở Nhật, tôi đã rất vất vả.",
"今４月にしては、ちょっと暑いですね。": "Bây giờ là tháng 4 mà thế này thì hơi nóng nhỉ.",
"彼女に愛を込めて手紙を書きました。": "Tôi đã viết cho cô ấy một lá thư chan chứa tình yêu.",
# --- hand-authored fallback examples (source pages blocked by anti-bot challenge) ---
"どうしても行きたいなら、止めないよ。": "Nếu bằng mọi giá cậu vẫn muốn đi thì tôi không ngăn đâu.",
"この問題はどうしても解けない。": "Bài toán này tôi cố mãi mà không giải được.",
"さて、そろそろ始めましょうか。": "Nào, chúng ta bắt đầu thôi nhỉ.",
"さて、次の話題に移ります。": "Vậy thì, chuyển sang chủ đề tiếp theo.",
"しばらくお待ちください。": "Xin vui lòng đợi một lát.",
"しばらく日本語を勉強していなかった。": "Một thời gian rồi tôi không học tiếng Nhật.",
"彼はすでに帰ってしまった。": "Anh ấy đã về mất rồi.",
"その店はすでに閉まっていた。": "Cửa hàng đó đã đóng cửa rồi.",
"彼は私の母の弟、すなわち叔父です。": "Anh ấy là em trai của mẹ tôi, tức là cậu tôi.",
"日本の首都、すなわち東京に住んでいます。": "Tôi sống ở thủ đô Nhật Bản, tức là Tokyo.",
"この仕事は三日はかかる。": "Công việc này mất ít nhất ba ngày.",
"修理には一万円はかかるだろう。": "Sửa chữa chắc mất ít nhất một vạn yên.",
"この程度のけがなら薬を塗るだけで済む。": "Vết thương cỡ này chỉ cần bôi thuốc là xong.",
"電話で済むことなら、わざわざ行かなくていい。": "Nếu là việc gọi điện là xong thì không cần mất công đi.",
"今はテレビを見ている場合じゃない。": "Bây giờ không phải lúc để xem tivi.",
"のんびりしている場合じゃないよ。急ごう。": "Không phải lúc thong thả đâu. Nhanh lên.",
"今さら後悔しても始まらない。": "Bây giờ có hối hận cũng vô ích.",
"文句を言っても始まらないから、やるしかない。": "Có kêu ca cũng chẳng ích gì, nên đành phải làm thôi.",
"急いで駅に行った。ところが、電車はもう出ていた。": "Tôi vội vàng ra ga. Thế nhưng tàu đã chạy mất rồi.",
"晴れると思っていた。ところが、急に雨が降り出した。": "Tôi cứ nghĩ trời sẽ nắng. Vậy mà bỗng dưng trời đổ mưa.",
"彼は疲れているように見える。": "Trông anh ấy có vẻ mệt.",
"この絵は本物のように見える。": "Bức tranh này trông như thật.",
"彼は自分の間違いを認めようとしない。": "Anh ta không chịu thừa nhận lỗi của mình.",
"息子は全然勉強しようとしない。": "Con trai tôi chẳng chịu học hành gì cả.",
}
